### ISSUE TITLE
__init__.py gets clobbered when installing multiple jaraco python packages

### ISSUE THREAD

**Issue by teake** [jaraco/jaraco.collections#6]
Because `jaraco/__init__.py` exists in all jaraco.* python packages, it gets clobbered when installing two or more of them in the same environment. This is not a problem in itself, but [conda complains about it when installing the downstream packages](https://github.com/conda-forge/jaraco.collections-feedstock/issues/4). (See also conda/conda#9849).

I've read through https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages but, having limited experience with pkgutil, I am not sure if these `__init__.py`  files are still needed in Python 3.3+ (cf. [PEP-420](https://www.python.org/dev/peps/pep-0420/)).

If they are not, could be removed? Thanks!

**Comment by jaraco** [comment]
Those files are required for pkgutil-style namespace packages. And you're right - now that jaraco packages no longer support Python 2.7, it should be possible to transition to native namespace packages. The one problem, however, is cross-library compatibility. If one package presents `jaraco` as a pkgutil-style namespace and another presents native, I'm not sure they interoperate well (or under what conditions they don't). For now, these projects are working as intended and the defect lies with conda in supporting this intentional overlap.
